environment:
  nuget_api_key:
    secure: kM3Kse+ivuuE5RVoe6dPdw+aguWx56K2YeXujGa9tMPQTms3lv7QxNpTLFMALYNa
  chocolatey_api_key:
    secure: VoMjz8m05p36wSWVftaYelpfzEBZjZx9EzvamZaNQx0evttLbtQtK1w0eXLrfDbj
      
platform: Any CPU

configuration: Release

install:
  - cinst gitversion.portable -y
  - cinst gitlink -y

before_build:
  - nuget restore Source\LynxToolkit.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/LynxToolkit.sln
  verbosity: minimal

after_build:
  - cmd: gitlink c:\projects\lynx-toolkit -u https://github.com/objorke/lynx-toolkit -b master -f Source/LynxToolkit.sln
  
deploy_script:
  - cmd: NuGet.exe pack Source\LynxToolkit.Documents\LynxToolkit.Documents.nuspec -version "%GitVersion_NuGetVersion%"
  - cmd: NuGet.exe pack Source\LynxToolkit.Documents.Html\LynxToolkit.Documents.Html.nuspec -version "%GitVersion_NuGetVersion%"
  - cmd: NuGet.exe pack Source\LynxToolkit.Documents.OpenXml\LynxToolkit.Documents.OpenXml.nuspec -version "%GitVersion_NuGetVersion%"
  - cmd: NuGet.exe pack Source\LynxToolkit.Documents.Wpf\LynxToolkit.Documents.Wpf.nuspec -version "%GitVersion_NuGetVersion%"
#  - cmd: for %%G in (NuGet\*.nupkg) do NuGet.exe push %%G %nuget_api_key%

  - cmd: mkdir Chocolatey
  - cmd: NuGet.Exe pack Source\LynxToolkit.nuspec -NoPackageAnalysis -NonInteractive -OutputDirectory Chocolatey -version "%GitVersion_NuGetVersion%"
#  - cmd: for %%G in (Chocolatey\*.nupkg) do NuGet.exe push %%G %chocolatey_api_key% -source http://chocolatey.org/ -NonInteractive

artifacts:
  - path: Output
    name: LynxToolkit-$(APPVEYOR_BUILD_VERSION)
